### Test root

GET http://127.0.0.1:8000/
Accept: application/json

### Test existing repo

GET http://127.0.0.1:8000/repo/Coins
Accept: application/json

### Test existing repo lowercase

GET http://127.0.0.1:8000/repo/coins
Accept: application/json

### Test unknown repo

GET http://127.0.0.1:8000/repo/Unknown
Accept: application/json

###
